Hello: Hit enter key for each beat (q to quit).
GoodBye: Bye Bye!
Tempo bpm@Float p@Int: Tempo: #{showBpm p bpm} bpm
HitMore: [Hit enter key one more time to start bpm computation...]

CLIHelp: show this help text
CLIVersion: display the version
CLIHeader: Tap Tempo measures the rythm of your key press
CLIDescription: Press the <Enter> key and see your rythm

CLIHelpPrecision: set the decimal precision of the tempo display
CLIHelpSampleSize: set the number of samples needed to compute the tempo
CLIHelpResetTime: set the time in second to reset the computation