Hello: Appuyer sur la touche entrée en cadence (q pour quitter).
GoodBye: Au revoir !
Tempo bpm@Float p@Int: Tempo : #{showBpm p bpm}
HitMore: [Appuyer encore sur la touche entrée pour lancer le calcul du tempo...]

CLIHelp: affiche ce message d'aide
CLIVersion: afficher la version
CLIHeader: Tap Tempo mesure le rythme de votre frappe
CLIDescription: Appuyez sur <Entrée> en rythme

CLIHelpPrecision: changer le nombre de décimale du tempo à afficher.
CLIHelpResetTime: changer le temps en seconde de remise à zéro du calcul.
CLIHelpSampleSize: changer le nombre d'échantillons nécessaires au calcul du tempo.